#!/nfs/goldstein/software/R-3.0.1/bin/Rscript

#Set memory for Java
options(java.parameters = "-Xmx4096m")
#Load Libraries
library("optparse")
library("xlsx")

#Functions
getScriptPath <- function(){
    cmd.args <- commandArgs()
    m <- regexpr("(?<=^--file=).+", cmd.args, perl=TRUE)
    script.dir <- dirname(regmatches(cmd.args, m))
    if(length(script.dir) == 0) stop("can't determine script dir: please call the script with Rscript")
    if(length(script.dir) > 1) stop("can't determine script dir: more than one '--file' argument detected")
    return(script.dir)
}
#Function to return indices of LoF variants in functions list
ind.LoF <- function(data){
    LoF_var <- c(
    "STOP_GAINED",
    "START_LOST",
    "SPLICE_SITE_ACCEPTOR",
    "SPLICE_SITE_DONOR",
    "FRAME_SHIFT",
    "EXON_DELETED"
    )
    return 
}

#Function to return HGVSg given ATAV output with Variant.ID and Variant.Type 
HGVSg <- function(input, index=0){
    if(index == 0){inputVariants <- input[,c("Variant.ID","Variant.Type")]}
    else{inputVariants <- input[,c(paste0("Variant.ID.",index),paste0("Variant.Type.",index))]}
    out <- apply(inputVariants,1,function(x){
        if(x[2] == "snv"){
            x <- sub("-",">",sub("-","",sub("-",":g.",x[1])))}
        else if(x[2] == "indel"){
            tmpIndel <- strsplit(as.character(x[1]),"-")
            x <- paste0(tmpIndel[[1]][1],":g.",tmpIndel[[1]][2],"_",as.integer(tmpIndel[[1]][2])+nchar(tmpIndel[[1]][3])-1,"delins",tmpIndel[[1]][4])
        }
    })
    out <- as.data.frame(out)
    if(index == 0){colnames(out) <- "HGVSg"}
    else{colnames(out) <- paste0("HGVSg.",index)}
    return(out)
}


#Function to convert non-trio column names to trio names and perform additional non-trio filtering
nonTrioToTrio <- function(data){
    colnames(data)[which(colnames(data) %in% c("Sample.Name"))] <- c("Child")
    data <- data[which(
                       (data$subRVIS.Domain.Score <= 40 | 
                       is.na(data$subRVIS.Domain.Score)) &
                       (data$Polyphen.Humvar.Score >= .95 |
                       is.na(data$Polyphen.Humvar.Score))),]
    data <- data[which(!(data$Function %in% c("SYNONYMOUS_CODING","SYNONYMOUS_STOP","INTRON_EXON_BOUNDARY"))),]
    return(data)
}

##################################################################################################################
scriptPath <- getScriptPath()

#Opt parse
option_list = list(
    make_option(c("-c","--cmphet"), type="character", default="CHET/CHET_comphet.csv", help="Compound Heterozygous ATAV output file [default = CHET/CHET_comphet.csv]"),
    make_option(c("-d","--dnm"), type="character", default="DNM/DNM_denovoandhom.csv", help="Denovo Mutation ATAV output file [default = DNM/DNM_denovoandhom.csv]"),
    make_option(c("-o","--out"), type="character", default="variant_report.xlsx", help="Report output file [default  = variant_report.xlsx]"),
    make_option(c("-m","--mgi"), type="character", default=paste(scriptPath,"/MGI_essential.txt",sep=""), help="MGI essiential gene list [default  = <Script Path>/MGI_essential.txt]", dest="MGIe"),
    make_option(c("-n","--nontrio"), type="logical", default=F, action="store_true", help="Flag to process files as a non-trio, imposing additional filters to the tier one rules [default  = False]")
    )
    #make_option(c("-r","--raw"), type="character", default="atav_summary.xlsx", help="ATAV raw output summary excel [default = atav_summary.xlsx")

opt_parser = OptionParser(option_list=option_list)
opt = parse_args(opt_parser)


#read csv file as dataframe for dnm, chet, and add_anno, and MGI essential gene list
source(paste(scriptPath,"/trio_filters.R",sep=""))

MGIe <- read.table(opt$MGIe,header=T)

#Tier 1 filtering DNM 
#Merging additional annotations to table
dnm.data = read.csv(opt$dnm,na.strings="NA")
dnm.data <- cbind(dnm.data, gsub("'","",dnm.data$Gene.Name) %in% MGIe$Gene_symbol)
colnames(dnm.data)[dim(dnm.data)[2]] <- "MGI.Essential"
col.id <- grep("Gene.Name",colnames(dnm.data))
new.pos <- 3
dnm.data <- dnm.data[,c(1:(new.pos-1)[-col.id],col.id,c((new.pos):ncol(dnm.data))[-(col.id-new.pos+1)])]
col.id <- grep("Function",colnames(dnm.data))
new.pos <- 4
dnm.data <- dnm.data[,c(1:(new.pos-1)[-col.id],col.id,c((new.pos):ncol(dnm.data))[-(col.id-new.pos+1)])]

#de novo
if(opt$nontrio){
    dnm <- dnm.data[which(dnm.data$Genotype == "het"),]
    dnm <- nonTrioToTrio(dnm)
    pdnm <- dnm[which(do.call(paste,c(dnm[c("Child","Gene.Name")],sep="")) %in% names(table(do.call(paste,c(dnm[c("Child","Gene.Name")],sep="")))[which(table(do.call(paste,c(dnm[c("Child","Gene.Name")],sep=""))) == 1)])),]
    pchet <- dnm[which(do.call(paste,c(dnm[c("Child","Gene.Name")],sep="")) %in% names(table(do.call(paste,c(dnm[c("Child","Gene.Name")],sep="")))[which(table(do.call(paste,c(dnm[c("Child","Gene.Name")],sep=""))) > 1)])),]
}else{
    data <- Filter.by.Flag(dnm.data,'de novo', strict = TRUE)
    dnm <- Filter.for.denovo(data)
    data <- Filter.by.Allele.Count(data,19)
    tier2 <- Filter.for.tier2(data)
}
dnm <- cbind(dnm,HGVSg(dnm))
#Make IGV batch script
IGV_dir = file.path(dirname(opt$out),"IGV")
dir.create(IGV_dir,showWarnings=F)
write.table(dnm[,c("Family.ID","Child","Mother","Father","Flag","Variant.ID")],file=file.path(IGV_dir,"dnm.IGV.txt"),quote=F,row.names=F,sep="\t")
system(paste0(scriptPath,"/makeIGVbatch.sh ",file.path(IGV_dir,"dnm.IGV.txt")," 2>",file.path(IGV_dir,"dnm.IGV.log")),wait=F)
#Write VEP input file
write.csv(dnm, file = "denovo.csv")

#hemizygous
if(opt$nontrio){
    hem <- dnm.data[which(dnm.data$Genotype == "empty"),]
    hem <- nonTrioToTrio(hem)
}else{
    data <- Filter.by.Flag(dnm.data,'newly hemizygous', strict = TRUE) 
    hem <- Filter.for.hemizygous(data)
    data <- Filter.by.HemiHomo.Count(data,9)
    tier2 <- rbind(tier2,Filter.for.tier2(data))
}
hem <- cbind(hem, HGVSg(hem))
write.csv(hem, file = "hemizygous.csv")

#homozygous
if(opt$nontrio){
    hom <- dnm.data[which(dnm.data$Genotype == "hom"),] 
    hom <- nonTrioToTrio(hom)
}else{
    data <- Filter.by.Flag(dnm.data,'newly homozygous', strict = TRUE)  
    hom <- Filter.for.homozygous(data)
    data <- Filter.by.HemiHomo.Count(data,9)
    tier2 <- rbind(tier2,Filter.for.tier2(data))
}
hom <- cbind(hom, HGVSg(hom))
tier2 <- cbind(tier2, HGVSg(tier2))
write.csv(hom, file = "homozygous.csv")

if(opt$nontrio){chet<-dnm.data[which(dnm.data$Genotype == "empty"),]
}else{
#Filtering CHET and merging additional annotations to table for both variants
chet.data = read.csv(opt$cmphet,na.strings="NA") 
chet.data <- cbind(chet.data, gsub("'","",chet.data$Gene.Name) %in% MGIe$Gene_symbol)
colnames(chet.data)[dim(chet.data)[2]] <- "MGI.Essential"
col.id <- grep("Gene.Name",colnames(chet.data))
new.pos <- 3
chet.data <- chet.data[,c(1:(new.pos-1)[-col.id],col.id,c((new.pos):ncol(chet.data))[-(col.id-new.pos+1)])]
col.id <- grep("Function...1.",colnames(chet.data))
new.pos <- 4
chet.data <- chet.data[,c(1:(new.pos-1)[-col.id],col.id,c((new.pos):ncol(chet.data))[-(col.id-new.pos+1)])]
col.id <- grep("Function...2.",colnames(chet.data))
new.pos <- 5
chet.data <- chet.data[,c(1:(new.pos-1)[-col.id],col.id,c((new.pos):ncol(chet.data))[-(col.id-new.pos+1)])]

data <- Filter.by.Flag(chet.data,'compound heterozygote', strict = TRUE)  
chet <- Filter.for.compound.heterozygote(data)
data <- Filter.by.HemiHomo.Count(data,9,T)
tier2.chet <- Filter.for.tier2(data,T)

data <- Filter.by.Flag(chet.data,'possibly compound heterozygote', strict = TRUE)  
poschet <- Filter.for.compound.heterozygote(data)
colnames(chet) <- gsub("\\.\\.\\.([12]).",".\\1",colnames(chet))
colnames(poschet) <- gsub("\\.\\.\\.([12]).",".\\1",colnames(poschet))

chet <- cbind(chet, HGVSg(chet,1), HGVSg(chet,2))
poschet <- cbind(poschet, HGVSg(poschet,1), HGVSg(poschet,2))

write.csv(chet, file = "compound.heterozygote.csv")
write.csv(poschet, file = "possible.compound.heterozygote.csv")
chet <- rbind(chet,poschet)
data <- Filter.by.HemiHomo.Count(data,9,T)
tier2.chet <- rbind(tier2.chet, Filter.for.tier2(data,T))
colnames(tier2.chet) <- gsub("\\.\\.\\.([12]).",".\\1",colnames(tier2.chet))
tier2.chet <- cbind(tier2.chet, HGVSg(tier2.chet,1), HGVSg(tier2.chet,2))
}

#Make VEP input file
VEP_dir = file.path(dirname(opt$out),"VEP")
dir.create(VEP_dir,showWarnings=F)
write.table(c(as.vector(dnm$HGVSg),as.vector(hem$HGVSg),as.vector(hom$HGVSg),as.vector(chet$HGVSg.1),as.vector(chet$HGVSg.2),as.vector(tier2$HGVSg),as.vector(tier2.chet$HGVSg.1),as.vector(tier2.chet$HGVSg.2)),file=file.path(VEP_dir,"all_var.VEP.input"),quote=F,col.names=F,row.names=F)

#Create workbook and sheets
outwb <- createWorkbook()
sum.sheet <- createSheet(outwb, sheetName = "Summary")
if(!opt$nontrio){
    dnm.sheet <- createSheet(outwb, sheetName = "DNM")
    hem.sheet <- createSheet(outwb, sheetName = "HEM")
    hom.sheet <- createSheet(outwb, sheetName = "HOM")
    chet.sheet <- createSheet(outwb, sheetName = "CHET")
    tier2.sheet <- createSheet(outwb, sheetName = "Tier 2")
    tier2.chet.sheet <- createSheet(outwb, sheetName = "Tier 2(CHET)")
    addDataFrame(dnm, dnm.sheet, row.names=F, showNA=F)
    addDataFrame(hem, hem.sheet, row.names=F, showNA=F)
    addDataFrame(hom, hom.sheet, row.names=F, showNA=F)
    addDataFrame(chet, chet.sheet, row.names=F, showNA=F)
    addDataFrame(tier2, tier2.sheet, row.names=F, showNA=F)
    addDataFrame(tier2.chet, tier2.chet.sheet, row.names=F, showNA=F)
}else{
    dnm.sheet <- createSheet(outwb, sheetName = "pDNM")
    hem.sheet <- createSheet(outwb, sheetName = "pHEM")
    hom.sheet <- createSheet(outwb, sheetName = "pHOM")
    chet.sheet <- createSheet(outwb, sheetName = "pCHET")
    addDataFrame(pdnm, dnm.sheet, row.names=F, showNA=F)
    addDataFrame(hem, hem.sheet, row.names=F, showNA=F)
    addDataFrame(hom, hom.sheet, row.names=F, showNA=F)
    addDataFrame(pchet, chet.sheet, row.names=F, showNA=F)
}


#LoFd <- read.table(opt$LoFd,header=T)
sum = NULL
LoF_var <- c(
    "STOP_GAINED",
    "START_LOST",
    "SPLICE_SITE_ACCEPTOR",
    "SPLICE_SITE_DONOR",
    "FRAME_SHIFT",
    "EXON_DELETED"
)

#Create Summary Table
for(samp in unique(c(as.vector(dnm$Child),as.vector(hem$Child),as.vector(hom$Child),as.vector(chet$Child)))){

Ndnm <- length(which(dnm$Child==samp))
Nhem <- length(which(hem$Child==samp))
Nhom <- length(which(hom$Child==samp))
Nchet <- length(which(chet$Child==samp))
if(opt$nontrio){
    Ndnm <- length(which(pdnm$Child==samp))
    Nchet <- length(which(pchet$Child==samp))
}

samp.dnm.tierOne <- dnm[which(dnm$Child==samp),]
samp.hom.tierOne <- hom[which(hom$Child==samp),]
samp.hem.tierOne <- hem[which(hem$Child==samp),]
samp.chet.tierOne <- chet[which(chet$Child==samp),]
#HZ OMIM
samp.dnm.hzo <- samp.dnm.tierOne[which((samp.dnm.tierOne$Polyphen.Humvar.Score >= .95  | 
                                        samp.dnm.tierOne$Function %in%  LoF_var)  & 
                                        ((samp.dnm.tierOne$X0.1.RVIS..EVS. <= 25  &
                                         samp.dnm.tierOne$EdgeCase.EVS. == "N")  |
                                        (samp.dnm.tierOne$OEratio.tile.EVS. <= 25  &
                                         samp.dnm.tierOne$EdgeCase.EVS. == "Y")  |
                                        (samp.dnm.tierOne$GenicConstraint.EVS. <= 25)  |
                                        (samp.dnm.tierOne$X0.05._anypopn_RVIS.tile.ExAC. <= 25  &
                                         samp.dnm.tierOne$EdgeCase.EVS. == "N")  |
                                        (samp.dnm.tierOne$OEratio.tile.ExAC. <= 25  &
                                         samp.dnm.tierOne$EdgeCase.EVS. == "Y")  |
                                        (samp.dnm.tierOne$GenicConstraint_mis.z.tile.ExAC. <= 25))  &
                                        !is.na(samp.dnm.tierOne$OMIM.Disease.Name)),
                                ]$Gene.Name
samp.hzo <- gsub("'","",unique(c(as.vector(samp.dnm.hzo))))
#HZ Essential
samp.dnm.hze <- samp.dnm.tierOne[which((samp.dnm.tierOne$Polyphen.Humvar.Score >= .95  | 
                                        samp.dnm.tierOne$Function %in%  LoF_var)  & 
                                        ((samp.dnm.tierOne$X0.1.RVIS..EVS. <= 25  &
                                         samp.dnm.tierOne$EdgeCase.EVS. == "N")  |
                                        (samp.dnm.tierOne$OEratio.tile.EVS. <= 25  &
                                         samp.dnm.tierOne$EdgeCase.EVS. == "Y")  |
                                        (samp.dnm.tierOne$GenicConstraint.EVS. <= 25)  |
                                        (samp.dnm.tierOne$X0.05._anypopn_RVIS.tile.ExAC. <= 25  &
                                         samp.dnm.tierOne$EdgeCase.EVS. == "N")  |
                                        (samp.dnm.tierOne$OEratio.tile.ExAC. <= 25  &
                                         samp.dnm.tierOne$EdgeCase.EVS. == "Y")  |
                                        (samp.dnm.tierOne$GenicConstraint_mis.z.tile.ExAC. <= 25))  &
                                        (samp.dnm.tierOne$MGI.Essential == T)),
                                ]$Gene.Name
samp.hze <- gsub("'","",unique(c(as.vector(samp.dnm.hze))))
#ClinGen/Var LoF
haploinsufficient_or_recessive = c("Sufficient evidence","Nullizygosity")
samp.dnm.clin <- gsub("'","",samp.dnm.tierOne[which(samp.dnm.tierOne$Function %in% LoF_var &
                                (samp.dnm.tierOne$ClinGen.HaploinsufficiencyDesc == "Sufficient evidence" |
                                samp.dnm.tierOne$ClinVar.Pathogenic.Indel.Count > 0 |
                                samp.dnm.tierOne$Clinvar.Pathogenic.CNV.Count > 0 |
                                samp.dnm.tierOne$ClinVar.Pathogenic.SNV.Splice.Count > 0 |
                                samp.dnm.tierOne$ClinVar.Pathogenic.SNV.Nonsense.Count > 0)
                                ),]$Gene.Name)
samp.hom.clin <- gsub("'","",samp.hom.tierOne[which(samp.hom.tierOne$Function %in% LoF_var &
                                (samp.hom.tierOne$ClinGen.HaploinsufficiencyDesc %in% haploinsufficient_or_recessive |
                                samp.hom.tierOne$ClinVar.Pathogenic.Indel.Count > 0 |
                                samp.hom.tierOne$Clinvar.Pathogenic.CNV.Count > 0 |
                                samp.hom.tierOne$ClinVar.Pathogenic.SNV.Splice.Count > 0 |
                                samp.hom.tierOne$ClinVar.Pathogenic.SNV.Nonsense.Count > 0)
                                ),]$Gene.Name)
samp.hem.clin <- gsub("'","",samp.hem.tierOne[which(samp.hem.tierOne$Function %in% LoF_var &
                                (samp.hem.tierOne$ClinGen.HaploinsufficiencyDesc %in% haploinsufficient_or_recessive |
                                samp.hem.tierOne$ClinVar.Pathogenic.Indel.Count > 0 |
                                samp.hem.tierOne$Clinvar.Pathogenic.CNV.Count > 0 |
                                samp.hem.tierOne$ClinVar.Pathogenic.SNV.Splice.Count > 0 |
                                samp.hem.tierOne$ClinVar.Pathogenic.SNV.Nonsense.Count > 0) 
                                ),]$Gene.Name)
samp.1chet.clin <- gsub("'","",samp.chet.tierOne[which((samp.chet.tierOne$Function.1 %in% LoF_var | samp.chet.tierOne$Function.2 %in% LoF_var) &
                                (samp.chet.tierOne$ClinGen.HaploinsufficiencyDesc.1 == "Sufficient evidence" |
                                samp.chet.tierOne$ClinVar.Pathogenic.Indel.Count.1 > 0 |
                                samp.chet.tierOne$Clinvar.Pathogenic.CNV.Count.1 > 0 |
                                samp.chet.tierOne$ClinVar.Pathogenic.SNV.Splice.Count.1 > 0 |
                                samp.chet.tierOne$ClinVar.Pathogenic.SNV.Nonsense.Count.1 > 0 | 
                                samp.chet.tierOne$ClinVar.Pathogenic.Indel.Count.2 > 0 |
                                samp.chet.tierOne$Clinvar.Pathogenic.CNV.Count.2 > 0 |
                                samp.chet.tierOne$ClinVar.Pathogenic.SNV.Splice.Count.2 > 0 |
                                samp.chet.tierOne$ClinVar.Pathogenic.SNV.Nonsense.Count.2 > 0) 
                                ),]$Gene.Name)
samp.2chet.clin <- gsub("'","",samp.chet.tierOne[which((samp.chet.tierOne$Function.1 %in% LoF_var & samp.chet.tierOne$Function.2 %in% LoF_var) & 
                                (samp.chet.tierOne$ClinGen.HaploinsufficiencyDesc.1 %in% haploinsufficient_or_recessive)),]$Gene.Name)
samp.clin <- unique(c(as.vector(samp.dnm.clin),as.vector(samp.hom.clin),as.vector(samp.hem.clin),as.vector(samp.1chet.clin),as.vector(samp.2chet.clin)))

#LoF depleted/pLI
samp.dnm.LoF <- samp.dnm.tierOne[which(samp.dnm.tierOne$Function %in% LoF_var &
                                      ((samp.dnm.tierOne$LoF.FDR.EVS. < .01) |
                                      (samp.dnm.tierOne$LoF.FDR.ExAC. < .01) |
                                      (samp.dnm.tierOne$LoF.pLI.ExAC. > .9))),
                                      ]$Gene.Name
samp.hom.LoF <- samp.hom.tierOne[which(samp.hom.tierOne$Function %in% LoF_var &
                                      ((samp.hom.tierOne$LoF.FDR.EVS. < .01) |
                                      (samp.hom.tierOne$LoF.FDR.ExAC. < .01) |
                                      (samp.hom.tierOne$LoF.pLI.ExAC. > .9) |
                                      (samp.hom.tierOne$LoF.pRec.ExAC. > .9))),
                                      ]$Gene.Name
samp.hem.LoF <- samp.hem.tierOne[which(samp.hem.tierOne$Function %in% LoF_var &
                                      ((samp.hem.tierOne$LoF.FDR.EVS. < .01) |
                                      (samp.hem.tierOne$LoF.FDR.ExAC. < .01) |
                                      (samp.hem.tierOne$LoF.pLI.ExAC. > .9) |
                                      (samp.hem.tierOne$LoF.pRec.ExAC. > .9))),
                                      ]$Gene.Name
samp.1chet.LoF <- samp.chet.tierOne[which(samp.chet.tierOne$Function.1 %in% LoF_var &
                                      ((samp.chet.tierOne$LoF.FDR.EVS..1 < .01) |
                                      (samp.chet.tierOne$LoF.FDR.ExAC..1 < .01) |
                                      (samp.chet.tierOne$LoF.pLI.ExAC..1 > .9) |
                                      (samp.chet.tierOne$LoF.pRec.ExAC..1 > .9))), 
                                      ]$Gene.Name
samp.2chet.LoF <- samp.chet.tierOne[which(samp.chet.tierOne$Function.2 %in% LoF_var &
                                      ((samp.chet.tierOne$LoF.FDR.EVS..2 < .01) |
                                      (samp.chet.tierOne$LoF.FDR.ExAC..2 < .01) |
                                      (samp.chet.tierOne$LoF.pLI.ExAC..2 > .9) |
                                      (samp.chet.tierOne$LoF.pRec.ExAC..2 > .9))),
                                      ]$Gene.Name
samp.LoF <- gsub("'","",unique(c(as.vector(samp.dnm.LoF),as.vector(samp.hom.LoF),as.vector(samp.hem.LoF),as.vector(samp.1chet.LoF),as.vector(samp.2chet.LoF))))


#KnownVar HGMD
ind <- which(!is.na(samp.dnm.tierOne$HGMD.Pmid))
samp.dnm.KnownVar <- c(as.vector(samp.dnm.tierOne[ind,]$Gene.Name),as.vector(gsub("\\(\\)","",paste("(",samp.dnm.tierOne[ind,]$HGMD.Pmid,")",sep=""))))
ind <- which(!is.na(samp.hom.tierOne$HGMD.Pmid))
samp.hom.KnownVar <- c(as.vector(samp.hom.tierOne[ind,]$Gene.Name),as.vector(gsub("\\(\\)","",paste("(",samp.hom.tierOne[ind,]$HGMD.Pmid,")",sep=""))))
ind <- which(!is.na(samp.hem.tierOne$HGMD.Pmid))
samp.hem.KnownVar <- c(as.vector(samp.hem.tierOne[ind,]$Gene.Name),as.vector(gsub("\\(\\)","",paste("(",samp.hem.tierOne[ind,]$HGMD.Pmid,")",sep=""))))
ind <- which(!is.na(samp.chet.tierOne$HGMD.Pmid.1))
samp.1chet.KnownVar <- c(as.vector(samp.chet.tierOne[ind,]$Gene.Name),as.vector(gsub("\\(\\)","",paste("(",samp.chet.tierOne[ind,]$HGMD.Pmid.1,")",sep=""))))
ind <- which(!is.na(samp.chet.tierOne$HGMD.Pmid.2))
samp.2chet.KnownVar <- c(as.vector(samp.chet.tierOne[ind,]$Gene.Name),as.vector(gsub("\\(\\)","",paste("(",samp.chet.tierOne[ind,]$HGMD.Pmid.2,")",sep=""))))

#KnownVar ClinVar
ind <- grep("Patho",samp.dnm.tierOne$ClinVar.Clinical.Significance,ignore.case=T)
samp.dnm.KnownClinVar <- c(as.vector(samp.dnm.tierOne[ind,]$Gene.Name),as.vector(gsub("\\(\\)","",paste("(",samp.dnm.tierOne[ind,]$ClinVar.PubmedID,")",sep=""))))
ind <- grep("Patho",samp.hom.tierOne$ClinVar.Clinical.Significance,ignore.case=T)
samp.hom.KnownClinVar <- c(as.vector(samp.hom.tierOne[ind,]$Gene.Name),as.vector(gsub("\\(\\)","",paste("(",samp.hom.tierOne[ind,]$ClinVar.PubmedID,")",sep=""))))
ind <- grep("Patho",samp.hem.tierOne$ClinVar.Clinical.Significance,ignore.case=T)
samp.hem.KnownClinVar <- c(as.vector(samp.hem.tierOne[ind,]$Gene.Name),as.vector(gsub("\\(\\)","",paste("(",samp.hem.tierOne[ind,]$ClinVar.PubmedID,")",sep=""))))
ind <- grep("Patho",samp.chet.tierOne$ClinVar.Clinical.Significance.1,ignore.case=T)
samp.1chet.KnownClinVar <- c(as.vector(samp.chet.tierOne[ind,]$Gene.Name),as.vector(gsub("\\(\\)","",paste("(",samp.chet.tierOne[ind,]$ClinVar.PubmedID.1,")",sep=""))))
ind <- grep("Patho",samp.chet.tierOne$ClinVar.Clinical.Significance.2,ignore.case=T)
samp.2chet.KnownClinVar <- c(as.vector(samp.chet.tierOne[ind,]$Gene.Name),as.vector(gsub("\\(\\)","",paste("(",samp.chet.tierOne[ind,]$ClinVar.PubmedID.2,")",sep=""))))

samp.KnownVar <- gsub("'","",unique(c(as.vector(samp.dnm.KnownVar),as.vector(samp.hom.KnownVar),as.vector(samp.hem.KnownVar),as.vector(samp.1chet.KnownVar),as.vector(samp.2chet.KnownVar),as.vector(samp.dnm.KnownClinVar),as.vector(samp.hom.KnownClinVar),as.vector(samp.hem.KnownClinVar),as.vector(samp.1chet.KnownClinVar),as.vector(samp.2chet.KnownClinVar))))

samp.gcClinicalOMIM <- unique(gsub("'","",c(as.vector(samp.dnm.tierOne[which(!is.na(samp.dnm.tierOne$OMIM.Disease.Name)),]$Gene.Name),as.vector(samp.hem.tierOne[which(!is.na(samp.hem.tierOne$OMIM.Disease.Name)),]$Gene.Name),as.vector(samp.hom.tierOne[which(!is.na(samp.hom.tierOne$OMIM.Disease.Name)),]$Gene.Name),as.vector(samp.chet.tierOne[which(!is.na(samp.chet.tierOne$OMIM.Disease.Name.1)),]$Gene.Name),"-")))

samp.gcClinicalnonOMIM <- unique(gsub("'","",c(as.vector(samp.hzo),as.vector(samp.hze),as.vector(samp.LoF))))
samp.gcClinicalnonOMIM <- c(samp.gcClinicalnonOMIM[!samp.gcClinicalnonOMIM %in% samp.gcClinicalOMIM],"-")

samp.tier2gcClinicalOMIM <- unique(gsub("'","",c(as.vector(tier2[which(tier2$Child==samp),][which(!is.na(tier2[which(tier2$Child==samp),]$OMIM.Disease.Name)),]$Gene.Name),as.vector(tier2.chet[which(tier2.chet$Child==samp),][which(!is.na(tier2.chet[which(tier2.chet$Child==samp),]$OMIM.Disease.Name...1)),]$Gene.Name))))
samp.tier2gcClinicalOMIM <- c(samp.tier2gcClinicalOMIM[!samp.tier2gcClinicalOMIM %in% samp.gcClinicalOMIM],"-")
samp.tier2gcClinicalOMIM <- c(samp.tier2gcClinicalOMIM[!samp.tier2gcClinicalOMIM %in% samp.gcClinicalnonOMIM],"-")

sum <- rbind(sum,c(samp,Ndnm,Nhem,Nhom,Nchet,"",paste(samp.hze,collapse="\n"),paste(samp.hzo,collapse="\n"),paste(samp.clin,collapse="\n"),paste(samp.LoF,collapse="\n"),gsub("^\n*([^)]*\\)?)\n*$","\\1",paste(samp.KnownVar,collapse="\n")),"","",gsub("(.*) \\.","\\1",gsub("\n-","",gsub("^: -","",paste(samp.gcClinicalOMIM,sep=": ",collapse=": \n")))),gsub("(.*) \\.","\\1",gsub("\n-","",gsub("^: -","",paste(samp.gcClinicalnonOMIM,sep=": ",collapse=": \n")))),gsub("(.*) \\.","\\1",gsub("\n-","",gsub("^: -","",paste(samp.tier2gcClinicalOMIM,sep=": ",collapse=": \n"))))))
}

#Write Excel file

#colnames(sum) <- c("diagseq","DNM","HEM","HOM","CHET","Ethn","HZ[E]","HZ[OMIM]","ClinGen/Var[LoF]","LoF depleted/pLI","KnownVar(PMID)","Candidate Genetic Diagnosis","Pheno","GC Clinical Fit(H/M/L)")
sum <- rbind(c("diagseq","DNM","HEM","HOM","CHET","Ethn","HZ [E]","HZ [OMIM]","ClinGen / Var [LoF]","LoF depleted / pLI","KnownVar (PMID)","Candidate Genetic Diagnosis","Pheno","OMIM GC Clinical Fit (H/M/L)","non-OMIM GC Clinical Fit (H/M/L)","Tier 2 OMIM Clinical Fit (H/M/L)"),sum)

cellBlock <- CellBlock(sum.sheet,1,1,dim(sum)[1],dim(sum)[2])
colnames_style <- CellStyle(outwb) + Font(outwb,isBold=T) + Alignment(horizontal="ALIGN_CENTER",vertical="VERTICAL_CENTER")
csWrap <- CellStyle(outwb) + Alignment(horizontal="ALIGN_CENTER",vertical="VERTICAL_CENTER",wrapText=T)
csCenter <- CellStyle(outwb) + Alignment(horizontal="ALIGN_CENTER",vertical="VERTICAL_CENTER")
colList <- rep(list(csWrap),dim(sum)[2])
names(colList) <- seq(1,dim(sum)[2])

colList[dim(sum)[2]] <- list(csWrap )
addDataFrame(sum, sum.sheet, col.names=F, row.names=F,colnamesStyle = colnames_style,colStyle=colList)
border <- Border(color="black", position=c("TOP","BOTTOM","LEFT","RIGHT"),pen=c("BORDER_THIN","BORDER_THIN","BORDER_THIN","BORDER_THIN"))
CB.setBorder(cellBlock,border,sort(c(rep(1:(dim(sum)[1]),dim(sum)[2]))),c(rep(1:dim(sum)[2],(dim(sum)[1]))))
colname_border <- Border(color="black",position="BOTTOM",pen="BORDER_THICK")
CB.setBorder(cellBlock,colname_border,1,1:dim(sum)[2])

setRowHeight(getRows(sum.sheet,1),1,multiplier=3)
for(col in c(1,13,14,15,16)){
    setColumnWidth(sum.sheet,col,14)
}
for(col in c(7:12)){
    setColumnWidth(sum.sheet,col,11)
}
for(col in c(2:6)){
    setColumnWidth(sum.sheet,col,5)
}
redFill <- Fill(foregroundColor = "red", backgroundColor = "red")
for(col in c(7:11)){
    ind <- which(sum[,col] != "")
    if(length(ind) > 0){CB.setFill(cellBlock, redFill, ind, col)}
}
ind <- which(sum[,8] != "")
CB.setFill(cellBlock, redFill, ind, 8)
grayFill <- Fill(foregroundColor = "gray")
CB.setFill(cellBlock, grayFill, 1,6:dim(sum)[2])

excelColumn<- function(num){
    name <- "" 
    while(num > 0){
        m <- (num - 1) %% 26
        name <- paste(LETTERS[m+1],name,sep="")
        num <- floor((num-m)/26)
    }
    return(name) 
}

addAutoFilter(sum.sheet,paste0("A:",excelColumn(dim(sum)[2])))
addAutoFilter(dnm.sheet,paste0("A:",excelColumn(dim(dnm)[2])))
addAutoFilter(hom.sheet,paste0("A:",excelColumn(dim(hom)[2])))
addAutoFilter(hem.sheet,paste0("A:",excelColumn(dim(hem)[2])))
addAutoFilter(chet.sheet,paste0("A:",excelColumn(dim(chet)[2])))
addAutoFilter(tier2.sheet,paste0("A:",excelColumn(dim(tier2)[2])))
addAutoFilter(tier2.chet.sheet,paste0("A:",excelColumn(dim(tier2.chet)[2])))

createFreezePane(dnm.sheet,2,5)
createFreezePane(hom.sheet,2,5)
createFreezePane(hem.sheet,2,5)
createFreezePane(chet.sheet,2,6)
createFreezePane(tier2.sheet,2,5)
createFreezePane(tier2.chet.sheet,2,6)

saveWorkbook(outwb, opt$out)
closeAllConnections()






